create table public.chat (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  content text null,
  user_id text null,
  role text null,
  session_id uuid null default gen_random_uuid (),
  constraint chat_pkey primary key (id)
) TABLESPACE pg_default;

create index IF not exists chat_created_at_idx on public.chat using btree (created_at) TABLESPACE pg_default;